### ISSUE TITLE
Dockerization 

### ISSUE THREAD

**Issue by MaFe1401** [ramonmeza/PythonSSHServerTutorial#1]
Hi! I was following your tutorial and realized that the dockerization part is missing. Did you manage to do it in the end? I see you list OpenSSH as a prerequisite, I assume it is required for the dockerization? Does the docker container need an OpenSSH server? 

I managed to deploy this SSH server into a docker container, but I cannot access from outside the container, although I did the port mapping. I would be grateful if you could give me some details about the dockerization.

Thank you in advance @ramonmeza !

**Comment by ramonmeza** [comment]
I apologize for the wait. I've added the section on Dockerizing the application. OpenSSH needs to be installed within the Docker container, as you'll see in the Dockerfile I've supplied. Also, note that the SSH server address needs to be set to `0.0.0.0` when ran within the Docker container. If you followed along with the tutorial up to this point, the Dockerfile should just work for you.

I'll close the issue for now, but if you run into any other issues, please let me know and I'll get back sooner than later this time.
